"""Adicionando chave estrangeira (group_id) na tabela users

Revision ID: 2a00ef078ca5
Revises: e311fabf0880
Create Date: 2024-12-16 15:38:26.432868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a00ef078ca5'
down_revision: Union[str, None] = 'e311fabf0880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'users', 'user_group', ['group_id'], ['user_group_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    # ### end Alembic commands ###
