"""criacao_tabela_user_group

Revision ID: e311fabf0880
Revises: cd18239f3026
Create Date: 2024-12-16 15:34:20.096245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e311fabf0880'
down_revision: Union[str, None] = 'cd18239f3026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_group',
    sa.Column('user_group_id', sa.Integer(), nullable=False),
    sa.Column('user_group_name', sa.String(length=100), nullable=False),
    sa.Column('user_group_created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_group_updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_group_deleted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_group')
    # ### end Alembic commands ###
